### ISSUE TITLE
Prebid server?

### ISSUE THREAD

**Issue by josepowera** [darkweak/bidding-platform#1]
Why not use [prebid-server](https://github.com/prebid/prebid-server) and add missing GeoIP part. Some adapters are already using bidswitch as backend(https://github.com/prebid/prebid-server/search?q=bidswitch) and for xandr check appnexus folder.

**Comment by darkweak** [comment]
Hi @josepowera this repository was made to have the lightest setup to support the openrtb protocol with multiple providers. And because afaik prebid seems to not support a distributed cache (and have multiple cache storages across the world).
